services:
  webapp:
    build:
      dockerfile: Dockerfile
    image: nuzul:latest
    container_name: "nuzul"
    restart: always
    volumes:
      - .:/var/www/html
    networks:
        - proxy_network  # ✅ Connect to NPM's network (internal routing)
    ports:
      - "8820:80"    
networks:
  proxy_network:
    external: true  # ✅ Make sure this matches NPM's network